// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAENWCDm10arE95rUZYWZkDRFhot612cAk',
    appId: '1:636311781968:web:a8a949a26a987b225d8755',
    messagingSenderId: '636311781968',
    projectId: 'chatapp-28d7f',
    authDomain: 'chatapp-28d7f.firebaseapp.com',
    storageBucket: 'chatapp-28d7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyxrZsQCxqyLBWGikhmhjq_TdV4BaP5eQ',
    appId: '1:636311781968:android:a2a80ad5d449c5945d8755',
    messagingSenderId: '636311781968',
    projectId: 'chatapp-28d7f',
    storageBucket: 'chatapp-28d7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvVGvys3h94HqKfkTBhtwU1vWXxPCma9E',
    appId: '1:636311781968:ios:5dea1794afe5b2db5d8755',
    messagingSenderId: '636311781968',
    projectId: 'chatapp-28d7f',
    storageBucket: 'chatapp-28d7f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvVGvys3h94HqKfkTBhtwU1vWXxPCma9E',
    appId: '1:636311781968:ios:feee7e1f3c8e10e95d8755',
    messagingSenderId: '636311781968',
    projectId: 'chatapp-28d7f',
    storageBucket: 'chatapp-28d7f.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
